"""One wrapped LLM call that always returns a schema-validated Pydantic object.

Two backends sit behind the same `call_json` contract:

  - "anthropic" (default) — `client.messages.parse(output_format=<PydanticModel>)`, which
    validates the JSON inside the SDK call and exposes `.parsed_output`. Written against
    anthropic 0.121.0, whose surface was confirmed at build time by reading the installed
    package. `anthropic.APIError` is the common base of APIStatusError and APIConnectionError.
  - "openai" — any OpenAI-compatible Chat Completions endpoint (NVIDIA NIM, Together,
    Groq, vLLM, OpenAI itself). There is no `output_format` equivalent, so the schema is
    embedded in the prompt, `response_format` is negotiated down from json_schema to
    json_object to nothing depending on what the endpoint accepts, and validation happens
    here against the same Pydantic model.

Both backends feed the SAME retry loop, so the structural-correctness guarantees
(exactly 5 lessons, 0-based answer_index) hold identically whichever one is selected.

Selected with LLM_PROVIDER; see .env.example.
"""

import json
import logging
import os
import re
from collections.abc import Callable
from typing import TypeVar

import anthropic
from dotenv import load_dotenv
from pydantic import BaseModel, ValidationError

load_dotenv()

logger = logging.getLogger(__name__)

# --- Anthropic -------------------------------------------------------------------------
#
# NOT YET VERIFIED against the live /v1/models list — that needs an API key, which was not
# available when this was written. Run `python main.py --verify-models` to confirm them and
# record the output in NOTES.md (PLAN.md Directive 3). Until then, treat these as unconfirmed.
MODEL_PATHBUILDER = "claude-sonnet-5"
# Named by PLAN.md for cheap extraction/checks. The v1 slice makes no cheap-model call, so
# this constant is currently unused; it records the plan's intent, nothing more.
MODEL_CHEAP = "claude-haiku-4-5"

# --- OpenAI-compatible -----------------------------------------------------------------
# Defaults point at NVIDIA's hosted endpoint. The model slug is a STARTING GUESS, not a
# verified ID — run `python main.py --list-models` against your endpoint and set LLM_MODEL
# to whatever it actually reports.
DEFAULT_OPENAI_BASE_URL = "https://integrate.api.nvidia.com/v1"
# Confirmed against NVIDIA's live /v1/models list on 2026-08-11. Note it is m3, not m2 —
# the slug cannot be guessed from the model's public name, which is why --list-models exists.
DEFAULT_OPENAI_MODEL = "minimaxai/minimax-m3"

PROVIDERS = ("anthropic", "openai")

# Hard character budget on the source text handed to the model, so we never blow context.
MAX_SOURCE_CHARS = 60_000

T = TypeVar("T", bound=BaseModel)


class LLMError(Exception):
    """The model call failed, or could not produce output matching the requested schema."""


class _SchemaFailure(Exception):
    """Model output did not validate. Feeds the retry channel rather than aborting.

    `log` records whether the caller already logged this, so the retry loop's logging stays
    byte-identical to the single-backend version it replaced.
    """

    def __init__(self, cause: BaseException, *, log: bool = True):
        super().__init__(str(cause))
        self.cause = cause
        self.log = log


def provider() -> str:
    """Which backend to use. Read at call time so tests and .env can both drive it."""
    name = (os.getenv("LLM_PROVIDER") or "anthropic").strip().lower()
    if name not in PROVIDERS:
        raise LLMError(
            f"LLM_PROVIDER={name!r} is not supported. Use one of: {', '.join(PROVIDERS)}."
        )
    return name


def active_model() -> str:
    """The model ID for the active provider. LLM_MODEL overrides the per-provider default."""
    override = (os.getenv("LLM_MODEL") or "").strip()
    if override:
        return override
    return MODEL_PATHBUILDER if provider() == "anthropic" else DEFAULT_OPENAI_MODEL


def generator_id() -> str:
    """Identity of whatever produces lessons, for cache keying.

    Without this in the key, switching provider or model serves lessons generated by the
    OTHER model straight out of the cache, with nothing in the response saying so.
    """
    return f"{provider()}:{active_model()}"


def client() -> anthropic.Anthropic:
    if not os.getenv("ANTHROPIC_API_KEY"):
        raise LLMError(
            "ANTHROPIC_API_KEY is not set. Copy .env.example to .env and put your key in it."
        )
    return anthropic.Anthropic()


def openai_client():
    """Client for any OpenAI-compatible Chat Completions endpoint."""
    try:
        from openai import OpenAI
    except ImportError as exc:  # pragma: no cover - dependency is pinned in requirements.txt
        raise LLMError(
            "LLM_PROVIDER=openai needs the openai package: pip install -r requirements.txt"
        ) from exc

    # .strip() because a key pasted into .env as `OPENAI_API_KEY= nvapi-...` is an easy typo
    # and surfaces as a confusing 401 rather than anything pointing at the whitespace.
    key = (os.getenv("OPENAI_API_KEY") or os.getenv("NVIDIA_API_KEY") or "").strip()
    if not key:
        raise LLMError(
            "Neither OPENAI_API_KEY nor NVIDIA_API_KEY is set. Copy .env.example to .env "
            "and put your key in it."
        )
    base_url = (os.getenv("OPENAI_BASE_URL") or DEFAULT_OPENAI_BASE_URL).strip()
    return OpenAI(api_key=key, base_url=base_url)


def truncate_source(text: str, budget: int = MAX_SOURCE_CHARS) -> str:
    """Cap source text at a fixed char budget. Returns the text unchanged if it fits."""
    if len(text) <= budget:
        return text
    return text[:budget] + "\n\n[SOURCE TRUNCATED AT {} CHARACTERS]".format(budget)


def verify_model(model_id: str) -> dict:
    """Confirm a model ID exists on the live models list (Directive 3).

    Called by `python main.py --verify-models`.
    """
    if provider() == "openai":
        import openai as openai_sdk

        api = openai_client()
        try:
            model = api.models.retrieve(model_id)
        except openai_sdk.NotFoundError:
            # Plenty of OpenAI-compatible hosts implement GET /v1/models but not
            # /v1/models/{id}. A 404 there says nothing about whether the model exists, so
            # fall back to the list rather than reporting a real model as missing.
            available = sorted(m.id for m in api.models.list())
            if model_id not in available:
                raise LLMError(
                    f"{model_id!r} is not served by this endpoint. "
                    f"Available: {', '.join(available) or '(none reported)'}"
                ) from None
            return {
                "id": model_id,
                "display_name": f"{model_id} (listed; no per-model endpoint)",
                "max_input_tokens": None,
                "max_tokens": None,
            }
        return {
            "id": model.id,
            "display_name": getattr(model, "owned_by", None) or model.id,
            "max_input_tokens": None,  # not exposed by the OpenAI models endpoint
            "max_tokens": None,
        }
    model = client().models.retrieve(model_id)
    return {
        "id": model.id,
        "display_name": model.display_name,
        "max_input_tokens": getattr(model, "max_input_tokens", None),
        "max_tokens": getattr(model, "max_tokens", None),
    }


def list_models() -> list[str]:
    """Every model ID the active endpoint advertises.

    Exists because an OpenAI-compatible host's model slugs are its own business — there is no
    way to know NVIDIA's exact ID for a model without asking it.
    """
    if provider() == "openai":
        return sorted(m.id for m in openai_client().models.list())
    return sorted(m.id for m in client().models.list())


# --- JSON extraction for the OpenAI-compatible path -------------------------------------

# Reasoning models (MiniMax M2 among them) emit <think>...</think> around their scratchpad.
# Some endpoints split it into `reasoning_content`; others leave it inline in the message.
_THINK_BLOCK = re.compile(r"<think\b[^>]*>.*?</think\s*>", re.DOTALL | re.IGNORECASE)
_UNCLOSED_THINK = re.compile(r"<think\b[^>]*>.*\Z", re.DOTALL | re.IGNORECASE)
_FENCE_OPEN = re.compile(r"^\s*```(?:json|JSON)?\s*", re.MULTILINE)
_FENCE_CLOSE = re.compile(r"\s*```\s*\Z")


def extract_json_object(text: str) -> str:
    """Pull the JSON object out of a chat completion's text.

    `messages.parse` does this inside the Anthropic SDK. On a raw Chat Completions endpoint
    nothing does, and the model may wrap the object in reasoning tags, markdown fences, or a
    sentence of preamble — none of which json.loads tolerates.
    """
    if not text or not text.strip():
        raise ValueError("model returned an empty message")

    cleaned = _THINK_BLOCK.sub("", text)
    cleaned = _UNCLOSED_THINK.sub("", cleaned)  # truncated mid-thought
    cleaned = _FENCE_OPEN.sub("", cleaned)
    cleaned = _FENCE_CLOSE.sub("", cleaned)

    start = cleaned.find("{")
    end = cleaned.rfind("}")
    if start == -1 or end <= start:
        raise ValueError(f"no JSON object found in model output: {text[:200]!r}")
    return cleaned[start : end + 1]


def _schema_instruction(schema_model: type[T]) -> str:
    """Put the schema in the prompt.

    The Anthropic backend gets this enforced by the SDK. An OpenAI-compatible endpoint may
    or may not honour response_format, so the schema has to be stated in prose as well —
    it is the only mechanism that works on every endpoint.
    """
    schema = json.dumps(schema_model.model_json_schema(), indent=2, sort_keys=True)
    return (
        "\n\nOutput format: return ONE JSON object and nothing else. No markdown fences, "
        "no commentary before or after, no reasoning in the reply. It must validate "
        "against this JSON Schema:\n\n"
        f"<json_schema>\n{schema}\n</json_schema>"
    )


# Negotiated once per process: endpoints differ on which response_format values they accept,
# and the only reliable way to find out is to be told no.
_NEGOTIATED_JSON_MODE: str | None = None
_JSON_MODES = ("json_schema", "json_object", "none")


def _json_modes_to_try() -> tuple[str, ...]:
    configured = (os.getenv("LLM_JSON_MODE") or "auto").strip().lower()
    if configured in _JSON_MODES:
        return (configured,)
    if configured != "auto":
        raise LLMError(
            f"LLM_JSON_MODE={configured!r} is not supported. "
            f"Use auto, {', '.join(_JSON_MODES)}."
        )
    if _NEGOTIATED_JSON_MODE is not None:
        return (_NEGOTIATED_JSON_MODE,)
    return _JSON_MODES


def _response_format(mode: str, schema_model: type[T]) -> dict | None:
    if mode == "json_schema":
        return {
            "type": "json_schema",
            "json_schema": {
                "name": schema_model.__name__.lower(),
                "schema": schema_model.model_json_schema(),
                "strict": False,  # Path uses $defs/$ref, which strict mode rejects
            },
        }
    if mode == "json_object":
        return {"type": "json_object"}
    return None


def _attempt_anthropic(
    api,
    *,
    system: str,
    messages: list[dict],
    schema_model: type[T],
    model: str,
    max_tokens: int,
    thinking: dict | None,
) -> T:
    kwargs: dict = {
        "model": model,
        "max_tokens": max_tokens,
        "system": system,
        "messages": messages,
        "output_format": schema_model,
    }
    if thinking is not None:
        kwargs["thinking"] = thinking

    try:
        response = api.messages.parse(**kwargs)
    except ValidationError as exc:
        # messages.parse validates inside the SDK call, so a response truncated at
        # max_tokens lands here as invalid JSON rather than reaching the stop_reason
        # check below. The final error message says so.
        raise _SchemaFailure(exc) from exc
    except anthropic.APIError as exc:
        # Covers APIStatusError (401/429/5xx) and APIConnectionError/APITimeoutError.
        # Wrapped so callers only ever handle LLMError.
        raise LLMError(f"Anthropic API call failed ({type(exc).__name__}): {exc}") from exc

    if response.stop_reason == "max_tokens":
        raise LLMError(
            f"Response hit max_tokens ({max_tokens}) and is incomplete. "
            "Raise max_tokens or shorten the source."
        )
    if response.stop_reason == "refusal":
        raise LLMError(f"Model refused the request. stop_details={response.stop_details}")

    parsed = response.parsed_output
    if parsed is None:
        raise _SchemaFailure(
            LLMError("Model returned no parseable structured output."), log=False
        )
    return parsed


def _merge_consecutive(messages: list[dict]) -> list[dict]:
    """Join runs of same-role messages into one.

    The retry path appends a second `user` turn. Anthropic combines consecutive same-role
    messages server-side; several OpenAI-compatible hosts reject them outright, so the retry
    would 400 instead of correcting the model.
    """
    merged: list[dict] = []
    for message in messages:
        if merged and merged[-1]["role"] == message["role"]:
            merged[-1] = {
                "role": message["role"],
                "content": f"{merged[-1]['content']}\n\n{message['content']}",
            }
        else:
            merged.append(dict(message))
    return merged


def _attempt_openai(
    api,
    *,
    system: str,
    messages: list[dict],
    schema_model: type[T],
    model: str,
    max_tokens: int,
) -> T:
    global _NEGOTIATED_JSON_MODE
    import openai as openai_sdk

    chat_messages = [
        {"role": "system", "content": system + _schema_instruction(schema_model)},
        *_merge_consecutive(messages),
    ]
    kwargs: dict = {"model": model, "max_tokens": max_tokens, "messages": chat_messages}
    temperature = (os.getenv("LLM_TEMPERATURE") or "").strip()
    if temperature:
        kwargs["temperature"] = float(temperature)

    response = None
    last_bad_request: Exception | None = None
    for mode in _json_modes_to_try():
        call_kwargs = dict(kwargs)
        response_format = _response_format(mode, schema_model)
        if response_format is not None:
            call_kwargs["response_format"] = response_format
        try:
            response = api.chat.completions.create(**call_kwargs)
        except openai_sdk.BadRequestError as exc:
            # Endpoints reject response_format values they don't implement. Step down the
            # ladder rather than failing outright, and remember what worked.
            last_bad_request = exc
            logger.warning("Endpoint rejected response_format=%s: %s", mode, exc)
            continue
        except openai_sdk.APIError as exc:
            raise LLMError(f"LLM API call failed ({type(exc).__name__}): {exc}") from exc
        else:
            _NEGOTIATED_JSON_MODE = mode
            break

    if response is None:
        raise LLMError(
            "Endpoint rejected every JSON output mode "
            f"({', '.join(_json_modes_to_try())}). Last error: {last_bad_request}"
        )

    if not response.choices:
        raise _SchemaFailure(LLMError("Model returned no choices."), log=False)

    choice = response.choices[0]
    if choice.finish_reason == "length":
        raise LLMError(
            f"Response hit max_tokens ({max_tokens}) and is incomplete. "
            "Raise max_tokens or shorten the source."
        )
    if choice.finish_reason == "content_filter":
        raise LLMError("Model refused the request (finish_reason=content_filter).")

    try:
        payload = extract_json_object(choice.message.content or "")
    except ValueError as exc:
        raise _SchemaFailure(exc) from exc

    try:
        return schema_model.model_validate_json(payload)
    except ValidationError as exc:
        raise _SchemaFailure(exc) from exc


def call_json(
    system: str,
    user: str,
    schema_model: type[T],
    *,
    model: str | None = None,
    max_tokens: int = 16_000,
    thinking: dict | None = None,
    post_validate: Callable[[T], list[str]] | None = None,
) -> T:
    """Ask the model for JSON matching `schema_model`, validate it, retry once on failure.

    `post_validate` returns a list of human-readable problems with an otherwise schema-valid
    object (e.g. a 1-based answer_index, or the wrong lesson count). Its failures feed the
    SAME retry channel as schema errors, because they describe exactly the kind of structural
    mistake a model can correct when told. This matters because neither backend enforces
    array bounds: the Anthropic SDK strips minItems/maxItems from the JSON schema it sends,
    and an OpenAI-compatible endpoint may ignore the schema entirely. In both cases the model
    is only told about them in prose.

    `thinking` is Anthropic-only and is ignored by the OpenAI-compatible backend, which has
    no equivalent parameter.

    Raises LLMError on any failure — validation failing twice over, a truncated or refused
    response, or a transport/status error. Never returns partial or invented data
    (Directive 7).
    """
    backend = provider()
    model = model or active_model()
    api = openai_client() if backend == "openai" else client()
    messages: list[dict] = [{"role": "user", "content": user}]

    last_error: BaseException | None = None
    last_error_from_schema = False
    for attempt in (1, 2):
        try:
            if backend == "openai":
                parsed = _attempt_openai(
                    api,
                    system=system,
                    messages=messages,
                    schema_model=schema_model,
                    model=model,
                    max_tokens=max_tokens,
                )
            else:
                parsed = _attempt_anthropic(
                    api,
                    system=system,
                    messages=messages,
                    schema_model=schema_model,
                    model=model,
                    max_tokens=max_tokens,
                    thinking=thinking,
                )
        except _SchemaFailure as failure:
            last_error = failure.cause
            last_error_from_schema = True
            if failure.log:
                logger.warning("Attempt %d: model output failed schema validation", attempt)
        else:
            if post_validate is not None and (problems := post_validate(parsed)):
                last_error = LLMError("; ".join(problems))
                last_error_from_schema = False
                logger.warning("Attempt %d: post-validation failed: %s", attempt, last_error)
            else:
                return parsed

        if attempt == 1:
            messages = [
                {"role": "user", "content": user},
                {
                    "role": "user",
                    "content": (
                        "Your previous response did not validate against the required schema "
                        "or broke one of the stated rules. Return the whole object again, "
                        "corrected. Emit only the JSON object and make sure it is complete "
                        "and closed.\n"
                        f"Problems to fix:\n{last_error}"
                    ),
                },
            ]

    if last_error_from_schema:
        raise LLMError(
            f"Model output failed schema validation on both attempts (max_tokens={max_tokens}). "
            "A common cause is the response being truncated at max_tokens mid-JSON, which "
            "surfaces as invalid JSON rather than a max_tokens stop reason — consider raising "
            f"max_tokens or shortening the source. Last error:\n{last_error}"
        )
    # The JSON was well-formed and schema-valid both times; the model simply would not follow
    # a stated rule. Saying "schema validation" here would point at the wrong thing entirely.
    raise LLMError(
        "Model returned schema-valid output that broke a stated rule on both attempts, so the "
        f"result was not usable. Unresolved problems:\n{last_error}"
    )
